name: CI/CD for TooClarity Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Remote Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Navigate to the project directory
            cd ~/tooclarity

            # Pull the latest code
            git pull origin main

            # Navigate to backend
            cd backend

            # Stop and remove any existing container
            docker stop tooclarity_backend || true
            docker rm tooclarity_backend || true

            # Build the Docker image
            docker build -t tooclarity-backend .

            # Run the new container
            docker run -d -p 3001:3001 --name tooclarity_backend tooclarity-backend

            echo "Deployment completed successfully."
          EOF
